# Generated by Django 5.1.3 on 2024-11-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
